//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Plugins {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Plugins() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Plugins", typeof(Plugins).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trivia stopped, your grade is: {0}.
        /// </summary>
        public static string Trivia_EndMessage {
            get {
                return ResourceManager.GetString("Trivia_EndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eror! in order to start enter Start , in order to finish enter EXIT..
        /// </summary>
        public static string Trivia_ErrorIncorrectTyping {
            get {
                return ResourceManager.GetString("Trivia_ErrorIncorrectTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer is invalid, You need to enter a number between 1 and 4.
        /// </summary>
        public static string Trivia_ErrorOutScope {
            get {
                return ResourceManager.GetString("Trivia_ErrorOutScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what the result of: {0} * {1} = {2}.
        /// </summary>
        public static string Trivia_Question {
            get {
                return ResourceManager.GetString("Trivia_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vary Good!!!.
        /// </summary>
        public static string Trivia_Success {
            get {
                return ResourceManager.GetString("Trivia_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to multiplication table trivia quiz, in order to start enter Start , in order to finish enter EXIT..
        /// </summary>
        public static string Trivia_Welcome {
            get {
                return ResourceManager.GetString("Trivia_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong, the correct answer is {0}.
        /// </summary>
        public static string Trivia_Wrong {
            get {
                return ResourceManager.GetString("Trivia_Wrong", resourceCulture);
            }
        }
    }
}
